apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: mongodb
  labels:
    app: mongodb-app
spec:
  type: LoadBalancer
  ports:
  - name:  mongodb
    port:  27017
    protocol: TCP
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb